### ISSUE TITLE
Presenting on view which is not in hierarchy

### ISSUE THREAD

**Issue by AdamZikmund** [tonyli508/LinkedinSwift#7]
Hi,
maybe would be nice to add support for specifying on which controller will be login screen presented.

**Comment by tonyli508** [comment]
Hi, I just pushed a new version, check it out, @AdamZikmund 

pod 'LinkedinSwift', '= 1.6.6'

**Comment by moazkh60** [comment]
This issue is still unresolved. It still says Presenting a view not in hierarchy.

**Comment by Isuru-Nanayakkara** [comment]
I'm also encountering this issue.
